apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: launcher
spec:
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: launcher-application
    weight: 100
  wildcardPolicy: None

