apiVersion: v1
kind: Secret
metadata:
  name: launcher
stringData:
  launcher.missioncontrol.openshift.clusters.subscription.token: {{ .Values.openshift.clusterSubscriptionToken | quote }}
  launcher.missioncontrol.openshift.username: {{ .Values.openshift.username | quote }}
  launcher.missioncontrol.openshift.password: {{ .Values.openshift.password | quote }}
  launcher.missioncontrol.openshift.token: {{ .Values.openshift.token | quote }}
  launcher.missioncontrol.github.token: {{ .Values.legacyGitProvider.github.token | quote }}
  launcher.missioncontrol.gitlab.token: {{ .Values.legacyGitProvider.gitlab.token | quote }}
  launcher.missioncontrol.bitbucket.username: {{ .Values.legacyGitProvider.bitbucket.username | quote }}
  launcher.missioncontrol.bitbucket.password: {{ .Values.legacyGitProvider.bitbucket.password | quote }}
  launcher.missioncontrol.gitea.username: {{ .Values.legacyGitProvider.gitea.username | quote }}
  launcher.missioncontrol.gitea.token: {{ .Values.legacyGitProvider.gitea.token | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: launcher-oauth-openshift
stringData:
  clientId: {{ .Values.oauth.clientId | quote }}
