kind: "Secret"
apiVersion: "v1"
metadata:
  name: "{{.secretName}}"
  labels:
    app: "{{.application}}"
stringData:
  uri: "{{.databaseUri}}"
  database: "{{.databaseName}}"
  user: "dbuser"
  password: "secret"  # TODO generate pwd
