objects:
- apiVersion: image.openshift.io/v1
  generation: 0
  image:
    dockerImageLayers: null
    dockerImageMetadata:
      ContainerConfig: {}
      Created: null
      Id: ''
      apiVersion: '1.0'
      kind: DockerImage
    dockerImageMetadataVersion: '1.0'
    metadata:
      creationTimestamp: null
  kind: ImageStreamTag
  lookupPolicy:
    local: false
  metadata:
    creationTimestamp: null
    labels:
      app: {{.application}}
    name: {{.serviceName}}:10
  tag:
    annotations: null
    from:
      kind: DockerImage
      name: 172.30.1.1:5000/openshift/postgresql:10
    generation: null
    importPolicy: {}
    name: '10'
    referencePolicy:
      type: ''
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: {{.application}}
    name: {{.serviceName}}
  spec:
    replicas: 1
    selector:
      app: {{.application}}
      deploymentconfig: {{.serviceName}}
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: {{.application}}
          deploymentconfig: {{.serviceName}}
      spec:
        containers:
        - image: 172.30.1.1:5000/openshift/postgresql:10
          name: {{.serviceName}}
          ports:
          - containerPort: 5432
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: {{.serviceName}}-volume-1
        volumes:
        - emptyDir: {}
          name: {{.serviceName}}-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - {{.serviceName}}
        from:
          kind: ImageStreamTag
          name: postgresql:10
          namespace: openshift
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: {{.application}}
    name: {{.serviceName}}
  spec:
    ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: {{.application}}
      deploymentconfig: {{.serviceName}}
  status:
    loadBalancer: {}
parameters: []
apiVersion: template.openshift.io/v1
kind: Template
